dist: trusty

sudo: required

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - /home/travis/.rvm/
    - "node_modules"

before_install:
 - sudo apt-get -qq update
 - gem install bundler
 - bundle check || bundle install

install:
  - sudo apt-get install -qq libxml2-utils libsaxonb-java docbook-xml

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - mkdir -p _temp/standards/ _temp/schema/dtd/docbkx45/
  - curl -o _temp/standards/standards.xml https://raw.githubusercontent.com/stavnstrup/nisp-tools/master/src/standards/standards.xml
  - cp -r /usr/share/xml/docbook/schema/dtd/4.5/* _temp/schema/dtd/docbkx45/
  - curl -o _temp/schema/dtd/stddb46.dtd https://raw.githubusercontent.com/stavnstrup/nisp-tools/master/src/schema/dtd/stddb46.dtd
  - xmllint --noout --valid _temp/standards/standards.xml
  - saxonb-xslt -ext:on _temp/standards/standards.xml _xsl/db2data.xsl
  - bundle exec jekyll build

deploy:
  - provider: script
    skip_cleanup: true
    script: "./_scripts/deploy-nisp-nation.sh"
    on:
      branch: master
